{% set name = "kubelogin" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 087d6828effb1e2e23015ef69e922c17920bf15e874e77916c28f63ba6db9c3e

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - posix  # [win]

test:
  commands:
    - kubelogin --version

about:
  home: https://github.com/Azure/kubelogin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a client-go credential (exec) plugin implementing azure authentication. This plugin provides features that are not available in kubectl. It is supported on kubectl v1.11+
  doc_url: https://github.com/Azure/kubelogin
  dev_url: https://github.com/Azure/kubelogin

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
