{% set name = "kubelogin" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Azure/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 98073ce2e755d3a9ba2e536b612e896bdfdbfa79e7ef074ee71071301ff1556e

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses >=1.2.1
    - posix  # [win]

test:
  commands:
    - kubelogin --version

about:
  home: https://github.com/Azure/kubelogin
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a client-go credential (exec) plugin implementing azure authentication. This plugin provides features that are not available in kubectl. It is supported on kubectl v1.11+
  doc_url: https://github.com/Azure/kubelogin
  dev_url: https://github.com/Azure/kubelogin

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
